name: Build and publish GitHub pages

on:
  push:
    branches:
      - main
      - master

jobs:
  pdoc:
    name: Build and publish GitHub pages
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Install pdoc
        run: uv add pdoc
      - name: Run pdoc
        run: uv run pdoc -d google --math -o docs {{cookiecutter.project_slug}}
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
{%- raw %}
          github_token: ${{ secrets.GITHUB_TOKEN }}
{%- endraw %}
          publish_dir: ./docs
